services:
  - type: web
    name: 2pixelblogs-discord-bot
    runtime: python
    repo: https://github.com/tamanhansalia/discord-todo-bot
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        value: MTQ5OTMxODQ1NjIyOTgyMjUyNQ.Gy-TGp.hIxio04F9vTnMIcK0WZMEqu-h-wuvyQv0yZtO0
      - key: PYTHON_VERSION
        value: 3.11.11
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py